### ISSUE TITLE
How to set version of postgresql ?

### ISSUE THREAD

**Issue by kopax-polyconseil** [ikalnytskyi/action-setup-postgres#14]
Hello @ikalnytskyi , I am testing your action and it seems it will install `posgresql`  version `14.6` in `/usr/local/Cellar/postgresql@14/14.6/bin/postgres`.

I would like to have version `12.9` , how can I change the version using your action ?

**Comment by ikalnytskyi** [comment]
Hey @kopax-polyconseil,

Unfortunately it's not possible to set custom PostgreSQL version at the moment. One of the foundational principles of this action was to use **preinstalled** PostgreSQL binaries. The rationale was simple:

- Make sure the action is fast and no installation is required.
- Make sure it's safe and doesn't reach out to external servers.
- Make sure it's auditable and everyone can verify it contains no malicious code.

I need to check how hard it would be to support parametrization on all three platforms before I can tell you is this someone on the roadmap or not.
