### ISSUE TITLE
macos-13 support: initdb command not found

### ISSUE THREAD

**Issue by baconcheese113** [ikalnytskyi/action-setup-postgres#16]
Thanks for all your work on this action!

In order to upgrade to flutter 3.10+, GPU passthrough is required, which is currently only supported on macos-13.

However when trying to use this action with macos-13 I get the following error
```
/Users/runner/work/_temp/978641ad-58d0-4713-94e7-f0fb921073ee.sh: line 19: initdb: command not found
```

**Comment by vaintroub** [comment]
It appears that postgres is not preinstalled on macos-13.
You can run 

    brew install postgresql@14

to install it yourself

**Comment by ikalnytskyi** [comment]
Since macOS 13 is still in Beta, I'd restrain from adding hacks to this action by detecting macOS version and installing PostgreSQL if it's 13.

I filed an issue to add PostgreSQL to macOS 13. Let's wait and see what the outcome will be. https://github.com/actions/runner-images/issues/9083

**Comment by pamelafox** [comment]
@ikalnytskyi I filed a similar issue that they closed, btw: https://github.com/actions/runner-images/issues/9029

**Comment by ikalnytskyi** [comment]
Oh, I see. @pamelafox, is this an issue related to ARM version of macOS 13? I haven't found PostgreSQL among preinstalled software for AMD64 architecture too.
