### ISSUE TITLE
The v4 releases source commit is not on any branch in the repository

### ISSUE THREAD

**Issue by dekimsey** [ikalnytskyi/action-setup-postgres#20]
It looks like the commit `v4` is based on, `fd37e265ec6a48981d62fa415f1fafd03bfd261c` isn't pushed to `master`. This is triggering a warning in the GH UI when looking at the release's commit.

The parent commit `f19cd589bfe54c9886202b25321dc302bbbb8e18` is on master. I'm guessing this is just a minor error where the default branch didn't get updated on release.

![image](https://github.com/ikalnytskyi/action-setup-postgres/assets/90741/80e248b3-6afd-4f74-bada-fc6bd6ab066e)

Thank you

**Comment by ikalnytskyi** [comment]
Ha, indeed. I wonder how it happened. The git diff shows no difference between fd37e265ec6a48981d62fa415f1fafd03bfd261c and f19cd589bfe54c9886202b25321dc302bbbb8e18. :thinking: It looks like the only difference is that the commit behind `v4` tag (fd37e265ec6a48981d62fa415f1fafd03bfd261c) is actually signed with my SSH key, while the commit in master is not.

Thanks for the reporting this, @dekimsey. I can either force push v4 tag that points to the commit in master, or make some v5 tag that is from master. What option do you think is preferable in your opinion?

**Comment by dekimsey** [comment]
I'd recommend simply publishing a new tag/release from master. v4 has been out since Jan 3rd of 2022, so I wouldn't recommend overwriting it. Packaging mistakes happen, I wouldn't worry about it. Just emit a new version with no other changes, after all numbers are free right? 😀

**Comment by dekimsey** [comment]
That is very true! However many such projects maintain a major version tag that is rewritten in addition to vX.Y.Z tags that do not.

If you want to rewrite tags, go for it. But I'd ask that you consider making permanent tags too so users may pin to a version they  know works for them.

**Comment by ikalnytskyi** [comment]
Hey @dekimsey,

I'm sorry for the delay. I just pushed the `v5` version that is tagged from `master`.

https://github.com/ikalnytskyi/action-setup-postgres/releases/tag/v5
