### ISSUE TITLE
Action failed because `brew link` step did not complete successfully.

### ISSUE THREAD

**Issue by YOCKOW** [ikalnytskyi/action-setup-postgres#27]
I'm not sure whether it is this action's issue or upstream's one, but `brew install postgresql@14` fails on macos-13 runner.

One of logs:
https://github.com/YOCKOW/SwiftPQ/actions/runs/8219886490/job/22478357746#step:2:137

**Comment by johanbrandhorst** [comment]
Also experiencing this.

**Comment by dekimsey** [comment]
So the root cause is how GHA installs Python and then injects it into the homebrew install paths, see Homebrew/homebrew-core#165793.

A quick and easy fix was simply removing any links into the Python install path.

```
- name: Remove GHA installed python symlinks that conflict with homebrew
  run: |
    find /usr/local/bin -lname '*/Library/Frameworks/Python.framework/*' -print -delete
- name: Launch PostgreSQL
  uses: ikalnytskyi/action-setup-postgres@74e396491e76c84f8ad92a4f5a69ab0deb75bbc2
```

**Comment by ikalnytskyi** [comment]
Thank you for reporting. It seems I managed to fix this in master, and I plan to release a new version somewhere next week, once I take care of other opened issues.
