### ISSUE TITLE
Use UTF-8 character set

### ISSUE THREAD

**Issue by chrisimcevoy** [ikalnytskyi/action-setup-postgres#3]
Hi, thanks for this great action! I have a hopefully small request please.

I am working on an ODBC library written in Python. My CI test matrix runs the test suite using different combinations of OS and DBMS.

On Windows with a PostgreSQL backend (created via this action), I get [one failed test](https://github.com/chrisimcevoy/purepyodbc/runs/6928659264?check_suite_focus=true#step:12:151). It is a round-trip of inserting/reading a UTF-8 string to check that what is read matches what was inserted. The same test passes for all other combinations of OS and DBMS, but for Postgres on Windows I get this error back from the ODBC driver:

`22P05ERROR: character with byte sequence 0xf0 0x9f 0x8c 0x9c in encoding "UTF8" has no equivalent in encoding "WIN1252"`

This error occurs on the `insert` SQL statement. The issue is that the database has a character encoding of WIN1252 and the unusual UTF-8 character in the string cannot be converted to the server's encoding. ([SO link](https://stackoverflow.com/questions/1565234/character-with-encoding-utf8-has-no-equivalent-in-win1252))

Would it be possible for the database to be created with UTF-8 character set? That way, I would be able to insert and read back the string in this test.

I'm not an expert, but I think I am asking for something like [this](https://www.postgresql.org/docs/devel/multibyte.html#id-1.6.11.5.6):

`initdb -E UTF8`

**Comment by ikalnytskyi** [comment]
Hey @chrisimcevoy,

Thanks for reporting the issue. I'll see what I can do. Let me check some docs regarding client/server encodings and encoding negotiation (if any).

**Comment by ikalnytskyi** [comment]
I have published `ikalnytskyi/action-setup-postgres@v3` where `encoding=UTF-8` and `locale=en_US.UTF-8` are enforced on Linux, macOS and Windows runners.
