### ISSUE TITLE
Bump version for macOS14 support

### ISSUE THREAD

**Issue by thrasher-** [ikalnytskyi/action-setup-postgres#33]
First of all thank you for this great GHA! Noticed that one of our actions is failing due to macos-latest being v14 now and was wondering when the next version will be published?

**Comment by ikalnytskyi** [comment]
Hey @thrasher-,

Thanks for reaching out. I'm sorry, I initially planned to deliver https://github.com/ikalnytskyi/action-setup-postgres/pull/30/ first and make a release, but I faced some issues and now I don't know how to proceed.

I'll try to get back to this in the next couple of days. If I fail to come up with a solution, I'll make the release w/o it.

**Comment by ikalnytskyi** [comment]
v6 is out https://github.com/ikalnytskyi/action-setup-postgres/releases/tag/v6

**Comment by thrasher-** [comment]
Thank you @ikalnytskyi !
