### ISSUE TITLE
Remove LC_COLLATE test from CI tests

### ISSUE THREAD

**Issue by nyurik** [ikalnytskyi/action-setup-postgres#38]
See https://github.com/ikalnytskyi/action-setup-postgres/pull/35 -- CI tests break when used with PG 16 because per [release notes](https://www.postgresql.org/docs/16/release-16.html):

> Remove read-only server variables lc_collate and lc_ctype (Peter Eisentraut)
> Collations and locales can vary between databases so having them as read-only server variables was unhelpful.

**Comment by ikalnytskyi** [comment]
I don't think removing the test is what we should do. The point of the test is to check default configuration of the PostgreSQL server from a user point of view. There's a big difference between having locale being set to `C` or `C.UTF-8` or `en_US.UTF-8` or something else. It does affect sort order (i.e. `ORDER BY`) of strings and may lead to flaky tests if we don't control it.

It goes without saying that I'd expect consumers to set proper collation on per-column basis in their database schema. However, as a maintainer of general purpose action, I have to come up with a default that just works, but most importantly, works the same regardless of the runner we're using.

I wasn't aware that LC_COLLATE and LC_CTYPE are gone now, yet I'd expect some kind of default value should exist in the configuration somewhere. Let me research a bit before making decision on how to proceed.
