### ISSUE TITLE
New user has no rights, and cannot be changed when default

### ISSUE THREAD

**Issue by nyurik** [ikalnytskyi/action-setup-postgres#7]
The createuser command used by this action creates `postgres` user without superuser abilities. This means I cannot do actions like `CREATE EXTENSION` and other critical actions. There may be a need for another parameter for the user access rights.  Thx!

**Comment by ikalnytskyi** [comment]
`ikalnytskyi/action-setup-postgres@v4` with superuser by default has been published. I'm closing this issue now. Please feel free to open a new ticket if this doesn't work for you.
